version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
